version: "3.7"

services:
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=perf-org
      - DOCKER_INFLUXDB_INIT_BUCKET=jmeter
      - DOCKER_INFLUXDB_INIT_RETENTION=1w
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-token

  grafana:
    image: grafana/grafana:9.3.6
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning

  jpetstore:
    image: jloisel/jpetstore6:latest
    container_name: jpetstore
    ports:
      - "8080:8080"

  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins
    privileged: true
    user: root
    ports:
      - "8081:8080" # Jenkins runs on host port 8081 (Internal 8080)
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    
    # --- ADDED HEALTH CHECK ---
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/login"] # Checks internal Jenkins port 8080
      interval: 10s
      timeout: 5s
      retries: 30 # Retries for up to 5 minutes to wait for Jenkins startup

volumes:
  jenkins_home:
